#server:
#    port: 8080
spring:
    application:
        name: ws
    redis:
        database: 0
        host: 127.0.0.1
        jedis:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 8
        password: ''
        port: 6379
        timeout: 5000

server:
    port: 443
    ssl:
        key-store: server.keystore
        key-alias: tomcat
        enabled: true
        key-store-password: 123456
        key-store-type: JKS